# -*- coding: utf-8 -*-
"""Relatório dados Covid-19 - São José dos Campos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18a2OjbHhRPS93-Ckm2rZd2LOTqEq0DHK

Os dados foram extraidos dos informes oficiais da prefeitura da cidade. Podem ser verificados em sua integra [aqui](https://www.sjc.sp.gov.br/servicos/saude/coronavirus/informe-epidemiologico/):
"""



import pandas as pd
path = '/content/drive/My Drive/covid-sjc .csv'
data_covid = pd.read_csv(path, sep=',')

"""## Gráficos"""

import matplotlib.pyplot as plt
plt.plot(data_covid['day0'],data_covid['cases_confirm'])
plt.title('Casos confirmados por dias da doença em SJC')
plt.xlabel('Dias a partir do 1o caso ')
plt.ylabel('Casos confirmados ')
plt.show()

plt.plot(data_covid['day0'],data_covid['recovery'])
plt.title('Recuperação dos casos')
plt.xlabel('Dias a partir do 1o caso ')
plt.ylabel('Casos recuperados ')
plt.show()

plt.plot(data_covid['day0'],data_covid['cases_suspect'])
plt.title('Variação dos casos confirmados em SJC')
plt.xlabel('Dias a partir do 1o caso ')
plt.ylabel('Casos suspeitos ')
plt.show()

plt.plot(data_covid['day0'],data_covid['recovery'], color='blue', label='Casos recuperados')
plt.plot(data_covid['day0'],data_covid['cases_confirm'], color='purple', label='Casos confirmados')
plt.plot(data_covid['day0'],data_covid['deaths'],  color='red', label='Óbitos')
plt.title('Comparação de casos confirmado, recuperação e morte em SJC')
plt.legend()
plt.xlabel('Dias a partir do 1o caso ')
plt.ylabel('Número de casos ')
plt.show()

plt.plot(data_covid['day0'],data_covid['deaths'],  color='red')
plt.title('Crescimento dos óbitos em SJC')
plt.xlabel('Dias a partir do 1o caso ')
plt.ylabel('Número de casos ')
plt.show()

"""## Números espeficíficos

### Maior quatidade de morte confirmada
"""

data_covid['deaths_day'].max()

"""### Maior crescimento de casos por 24h"""

data_covid['cases_confirm_day'].max()



"""## Taxa de óbito"""

data_covid['deaths'].max() * 100 / data_covid['cases_confirm'].max()

"""## Taxa de recuperação"""

data_covid['recovery'].max() * 100 / data_covid['cases_confirm'].max()